version: 1.0.{build}
before_build:
- cd PickupMailViewer
- npm install -g gulp
- npm install
- node node_modules\gulp\bin\gulp.js
- cd ..
build:
  publish_wap: true
  verbosity: minimal
artifacts:
- path: Deploy
  name: MailViewerWebDeploy
  type: WebDeployPackage